apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: conditional-dag-workflow
spec:
  entrypoint: conditional-dag
  templates:
  - name: conditional-dag
    dag:
      tasks:
      - name: condition-check
        template: condition-check-template
        arguments:
          parameters:
          - name: conditionParam
            valueFrom:
              configMapKeyRef:
                name: the-map
                key: enableExecution
        withItems: [1]

      - name: task-1
        template: echo-template
        arguments:
          parameters:
          - name: message
            value: "Task 1 executed"

      - name: task-2
        template: echo-template
        arguments:
          parameters:
          - name: message
            value: "Task 2 executed"

  - name: condition-check-template
    container:
      image: alpine
      command: [sh, -c]
      args: |
        if [ '{{inputs.parameters.conditionParam}}' == 'true' ]; then 
          echo "Condition succeeded"
        else
          echo "Condition failed"
          kubectl patch wf {{workflow.name}} -n {{workflow.namespace}} --type='merge' -p '{"status":{"phase":"Blocked", "customStatus":"block"}}'
          exit 1
        fi

  - name: echo-template
    container:
      image: alpine
      command: [sh, -c]
      args: ["echo '{{inputs.parameters.message}}'"]
